#!/bin/bash

get_theme() {
    # Check which waybar theme is set
    THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f3)

    #if the theme is not dark then we need to switch to it
    if [[ $THEMEIS == "dark.css" ]]; then
        SWITCHTO="-dark"
        MODESTR="Dark"
    else
        SWITCHTO=""
        MODESTR="Light"
    fi
}

get_ver() {
    VER=$(readlink -f ~/.config/waybar/config.jsonc | cut -d '-' -f1 | cut -d '/' -f8)
}

set_current_background() {
    get_theme
    get_ver
    #start swwww
    swww query || swww init
    #set the current background
    if [[ $THEMEIS == "dark.css" ]]; then
        swww img ~/.config/HyprV/backgrounds/$VER'-background-dark.jpg'
    else
        swww img ~/.config/HyprV/backgrounds/$VER'-background.jpg'
    fi
}

switch_version() {
    get_theme
    get_ver
    case $VER in
        v1)
            #we are on v1 so switch to v2
            VERTO="v2-"
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to HyprV2"
        ;;
        
        v2)
            #we are on v2 so switch to v3
            VERTO="v3-"
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to HyprV3"
        ;;

        v3)
            #we are on v3 so switch to v1
            VERTO="v1-"
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to HyprV1"
        ;;
    esac
    #set the waybar config
    ln -sf ~/.config/HyprV/waybar/conf/$VERTO'config.jsonc' ~/.config/waybar/config.jsonc
    #set the waybar theme
    ln -sf ~/.config/HyprV/waybar/style/$VERTO'style'$SWITCHTO.css ~/.config/waybar/style.css
    #set the wofi theme
    ln -sf ~/.config/HyprV/wofi/style/$VERTO'style'$SWITCHTO.css ~/.config/wofi/style.css

    #set the background
    swww img ~/.config/HyprV/backgrounds/$VERTO'background'$SWITCHTO.jpg --transition-fps 60 --transition-type wipe --transition-duration 2

    #restart the waybr
    pkill waybar
    exec waybar

}

if [[ "$1" == "vswitch" ]]; then
    switch_version
elif [[ "$1" == "setbg" ]]; then
    set_current_background
fi

# need to show the version and tooltip
get_ver

TOOLTIP='Default Keybinds\n'\
'SUPER + Q = Start Kitty\n'\
'SUPER + F4 = Close Window\n'\
'SUPER + L = Lock Screen\n'\
'SUPER + M = Logout menu\n'\
'SUPER + E = File Manager\n'\
'SUPER + V + Toggle Float\n'\
'SUPER + SPACE = App Launcher\n'\
'SUPER + S = Screenshot'

echo '{"text": "'$VER'", "tooltip": "'$TOOLTIP'"}'